import argparse

import colorama

from .. import __version__
from . import constants


def tm_colorama() -> colorama:
    """ Wrapper around colorama module with feature to disable the colored output

    Returns:
        colorama: Colorama module ready for use
    """
    from telemonitor.__main__ import args

    colorama_obj = colorama

    if args.disable_colored_output:
        # Overwrite all class variables with empty string to disable colored print
        for attr in ("Back", "Cursor", "Fore", "Style"):
            attr_dict = getattr(colorama_obj, attr).__dict__

            for k in attr_dict:
                attr_dict[k] = ""

    return colorama_obj


def cli_arguments_parser() -> object:
    """ Parse all startup arguments

    Returns:
        object: Namespace object, generated by `argparse` module
    """
    argparser = argparse.ArgumentParser(
        prog=constants.STRS.name,
        description=constants.STRS.description,
    )
    argparser.add_argument('--version', action='version', version=f'%(prog)s {__version__}')
    argparser.add_argument('--no-color', action='store_true', dest='disable_colored_output', help='disable colored output (ANSI escape sequences)')

    bot_group = argparser.add_argument_group('bot control optional arguments')
    bot_group.add_argument('--token', action='store', type=str, dest='token_overwrite', metavar='STR', help='force the bot to run with token from the argument instead of the configuration file')
    bot_group.add_argument('--whitelist', action='store', type=int, dest='whitelist_overwrite', metavar='INT', nargs='+', help='force the bot to check whitelisted users from argument instead of the of the configuration file')

    adv_group = argparser.add_argument_group('advanced optional arguments')
    adv_group.add_argument('--dev', help='enable unstable development features', action='store_true', dest='dev_features')
    adv_group.add_argument('--verbose', '-v', help='write debug information to log file', action='store_true')
    adv_group.add_argument('--config-check', action='store_true', help='run config file initialization procedure and exit', dest='config_check_only')
    adv_group.add_argument('--no-config-check', action='store_true', help="don't scan configuration file on start", dest='disable_config_check')
    adv_group.add_argument('--no-logging', action='store_true', help='disable logging system', dest='disable_logging')

    subparsers = argparser.add_subparsers(dest='command')

    # Subparser for `systemd service` control cli
    systemd_service_parser = subparsers.add_parser('service', help="linux systemd telemonitor service control")
    systemd_service_commands = systemd_service_parser.add_subparsers(dest='service_cli_command', metavar='command', required=True)
    systemd_service_commands.add_parser('install', help='install the service to system')
    systemd_service_upgrade = systemd_service_commands.add_parser('upgrade', help='upgrade installed service file (if any updates available)')
    systemd_service_commands.add_parser('apply', help='apply changes from configuration file to service')
    systemd_service_commands.add_parser('status', help='get status information of service')
    systemd_service_commands.add_parser('remove', help='remove service from system')

    systemd_service_upgrade.add_argument('-y', '--yes', action='store_true', dest='user_const_argreement', help='upgrade service without asking user permission')

    return argparser.parse_args()


def print_action(text: str, *args, start=""):
    """ Special function for printing the actions in standardized way

    Args:
        text (str): Text to print to the STDOUT
        start (str): Insert any text in the beginning of final string
    """
    __colorama = tm_colorama()

    def __colored_print(text: str):
        print(start + __colorama.Fore.LIGHTCYAN_EX + "[+] " + __colorama.Fore.RESET + text)

    __colored_print(text)

    if len(args) > 0:
        for text in args:
            __colored_print(text)


def ask_user_permission(ask_text: str) -> bool:
    """
    Create input and wait for user to agree or disagree.
    No input will be awaited if `CLI` parser will detect `user_const_argreement` var

    Args:
        ask_text (str): Confirmation message

    Returns:
        bool: Was action confirmed
    """
    from telemonitor.__main__ import args

    if args.user_const_argreement:
        return True

    __colorama = tm_colorama()
    input_action = input(f"{ask_text} {__colorama.Fore.GREEN}[y/n]{__colorama.Fore.RESET}: ")

    return True if input_action.lower() == 'y' else False
